// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PretestInternet() {
  return window['go']['app']['App']['PretestInternet']();
}

export function RebindPretest() {
  return window['go']['app']['App']['RebindPretest']();
}
